# Generated by Django 2.0.5 on 2018-05-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=10000)),
                ('body', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
